"""Spike for the "Hybrid RAG training-coach endpoint" Trello card, step 4
(web-search fallback + KB ingestion).

Question under test: can one Claude call combine web_search + web_fetch (with
citations enabled) + a custom tool for provenance/quality/classification
metadata - producing citation blocks whose cited_text is extracted verbatim
by the API from the fetched page (not generated by the model), while also
calling the custom tool for structured metadata? The version-pinned docs
shipped in this project's virtualenv (see AGENTS.md) document each piece
separately but not this exact combination, so this observes it directly
against the real API instead of assuming it composes.

Also unverified and worth watching in the output: the exact shape of
web_fetch's `citations` param (guessed here as {"enabled": True}, mirroring
the document-block convention - the docs list it as a supported param without
showing its shape), and whether `strict: true` + an `anyOf` nullable-enum
field is accepted for the custom tool's input schema.

    uv run python -m scripts.spike_citations_ingestion "<swim training question>"

Dumps the full raw response to scripts/spike_citations_ingestion_output.json
and prints a human-readable summary to stdout.
"""

import json
import sys
from pathlib import Path

from app.config import settings as app_settings
from app.rag.clients import anthropic_client

OUTPUT_PATH = Path(__file__).parent / "spike_citations_ingestion_output.json"

_NULLABLE_ENUM = lambda values: {"anyOf": [{"type": "string", "enum": values}, {"type": "null"}]}  # noqa: E731

_SUBMIT_TOOL = {
    "name": "submit_ingestion_candidates",
    "description": (
        "Submit knowledge-base ingestion candidates for pages you fetched while "
        "answering. Call this once you've finished searching and fetching, "
        "alongside your normal answer text. One entry per fetched page you "
        "consider worth keeping in the knowledge base."
    ),
    "strict": True,
    "input_schema": {
        "type": "object",
        "properties": {
            "candidates": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "source_url": {"type": "string"},
                        "quality_score": {"type": "number"},
                        "quality_flag": {"type": "string", "enum": ["pass", "reject"]},
                        "quality_reason": {"type": "string"},
                        "stroke_type": _NULLABLE_ENUM(
                            ["freestyle", "backstroke", "breaststroke", "butterfly", "individual_medley"]
                        ),
                        "topic_category": _NULLABLE_ENUM(
                            [
                                "technique",
                                "drills",
                                "training_science",
                                "recovery",
                                "nutrition",
                                "race_strategy",
                                "equipment",
                            ]
                        ),
                        "skill_level": _NULLABLE_ENUM(["beginner", "intermediate", "advanced", "elite"]),
                    },
                    "required": [
                        "source_url",
                        "quality_score",
                        "quality_flag",
                        "quality_reason",
                        "stroke_type",
                        "topic_category",
                        "skill_level",
                    ],
                    "additionalProperties": False,
                },
            }
        },
        "required": ["candidates"],
        "additionalProperties": False,
    },
}

_TOOLS = [
    {"type": "web_search_20260209", "name": "web_search", "max_uses": 3},
    {
        "type": "web_fetch_20260209",
        "name": "web_fetch",
        "max_uses": 2,
        "citations": {"enabled": True},
    },
    _SUBMIT_TOOL,
]

_SYSTEM = (
    "You are a swim coach assistant answering a training question using live web "
    "search. Search the web, fetch the most relevant page(s), and answer the "
    "swimmer's question grounded in what you found. After answering, call "
    "submit_ingestion_candidates once, listing every page you fetched that's "
    "worth keeping in a knowledge base for future questions."
)

_DEFAULT_QUESTION = "What's a good technique drill for improving my catch in freestyle?"


def main() -> None:
    question = sys.argv[1] if len(sys.argv) > 1 else _DEFAULT_QUESTION
    print(f"Question: {question}\n")

    with anthropic_client.messages.stream(
        model=app_settings.coach_model,
        max_tokens=8000,
        system=_SYSTEM,
        tools=_TOOLS,
        messages=[{"role": "user", "content": question}],
    ) as stream:
        response = stream.get_final_message()

    OUTPUT_PATH.write_text(response.to_json())
    print(f"Full raw response saved to {OUTPUT_PATH}\n")

    print(f"stop_reason: {response.stop_reason}")
    print(f"content block types: {[block.type for block in response.content]}\n")

    for block in response.content:
        if block.type == "text":
            citations = getattr(block, "citations", None) or []
            print(f"--- text block (citations: {len(citations)}) ---")
            print(block.text[:500])
            for citation in citations:
                print(f"  citation: {citation}")
        elif block.type == "tool_use":
            print(f"--- tool_use: {block.name} ---")
            print(json.dumps(block.input, indent=2)[:2000])
        elif block.type == "server_tool_use":
            print(f"--- server_tool_use: {block.name} input={block.input} ---")
        elif block.type in ("web_search_tool_result", "web_fetch_tool_result"):
            print(f"--- {block.type} ---")
            print(str(block.content)[:500])
        else:
            print(f"--- {block.type} (unhandled in this spike) ---")
        print()


if __name__ == "__main__":
    main()
