"""Variant of spike_citations_ingestion.py that forces allowed_callers: ["direct"]
on web_search and web_fetch, for the "Hybrid RAG training-coach endpoint" Trello
card, step 4 (web-search fallback + KB ingestion).

The original spike left allowed_callers unset, so web_search_20260209 and
web_fetch_20260209 defaulted to routing through code execution (dynamic
filtering). Two things broke there: every text block in the answer came back
with citations: null even though citations were requested and the content was
clearly pulled from the fetched pages, and continuing the conversation past
the model's submit_ingestion_candidates tool_use failed with a 400
("container_id is required when there are pending tool uses generated by code
execution with tools") because the response never actually included a
container object to reuse. Both point at the same cause: the model was
composing prose from code-execution print() output instead of the API's
native document/citation pipeline seeing the fetch result directly.

This variant sets allowed_callers: ["direct"] on both server tools to bypass
code execution entirely, to check whether that restores real citations and
avoids the container_id requirement (no code-execution-generated tool_use to
resolve, since nothing runs in a container).

    uv run python -m scripts.spike_citations_ingestion_direct "<swim training question>"

Dumps the full raw response to scripts/spike_citations_ingestion_direct_output.json
and prints a human-readable summary to stdout.
"""

import json
import sys
from pathlib import Path

from anthropic.types import Message

from app.config import settings as app_settings
from app.rag.clients import anthropic_client

OUTPUT_PATH = Path(__file__).parent / "spike_citations_ingestion_direct_output.json"
CONTINUATION_OUTPUT_PATH = Path(__file__).parent / "spike_citations_ingestion_direct_output_continued.json"

_NULLABLE_ENUM = lambda values: {"anyOf": [{"type": "string", "enum": values}, {"type": "null"}]}  # noqa: E731

_SUBMIT_TOOL = {
    "name": "submit_ingestion_candidates",
    "description": (
        "Submit knowledge-base ingestion candidates for pages you fetched while "
        "answering. Call this once you've finished searching and fetching, "
        "alongside your normal answer text. One entry per fetched page you "
        "consider worth keeping in the knowledge base."
    ),
    "strict": True,
    "input_schema": {
        "type": "object",
        "properties": {
            "candidates": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "source_url": {"type": "string"},
                        "quality_score": {"type": "number"},
                        "quality_flag": {"type": "string", "enum": ["pass", "reject"]},
                        "quality_reason": {"type": "string"},
                        "stroke_type": _NULLABLE_ENUM(
                            ["freestyle", "backstroke", "breaststroke", "butterfly", "individual_medley"]
                        ),
                        "topic_category": _NULLABLE_ENUM(
                            [
                                "technique",
                                "drills",
                                "training_science",
                                "recovery",
                                "nutrition",
                                "race_strategy",
                                "equipment",
                            ]
                        ),
                        "skill_level": _NULLABLE_ENUM(["beginner", "intermediate", "advanced", "elite"]),
                    },
                    "required": [
                        "source_url",
                        "quality_score",
                        "quality_flag",
                        "quality_reason",
                        "stroke_type",
                        "topic_category",
                        "skill_level",
                    ],
                    "additionalProperties": False,
                },
            }
        },
        "required": ["candidates"],
        "additionalProperties": False,
    },
}

_TOOLS = [
    {"type": "web_search_20260209", "name": "web_search", "max_uses": 3, "allowed_callers": ["direct"]},
    {
        "type": "web_fetch_20260209",
        "name": "web_fetch",
        "max_uses": 2,
        "citations": {"enabled": True},
        "allowed_callers": ["direct"],
    },
    _SUBMIT_TOOL,
]

_SYSTEM = (
    "You are a swim coach assistant answering a training question using live web "
    "search. Search the web, then use web_fetch to retrieve the full content of "
    "at least one of the most relevant pages you found - do not answer from "
    "search snippets alone, always fetch at least one page for the full detail. "
    "Answer the swimmer's question grounded in what you found. After answering, "
    "call submit_ingestion_candidates once, listing every page you fetched that's "
    "worth keeping in a knowledge base for future questions."
)

_DEFAULT_QUESTION = "What's a good technique drill for improving my catch in freestyle?"


def _print_response(response: Message) -> None:
    print(f"stop_reason: {response.stop_reason}")
    print(f"content block types: {[block.type for block in response.content]}\n")

    for block in response.content:
        if block.type == "text":
            citations = getattr(block, "citations", None) or []
            print(f"--- text block (citations: {len(citations)}) ---")
            print(block.text[:500])
            for citation in citations:
                print(f"  citation: {citation}")
        elif block.type == "tool_use":
            print(f"--- tool_use: {block.name} ---")
            print(json.dumps(block.input, indent=2)[:2000])
        elif block.type == "server_tool_use":
            print(f"--- server_tool_use: {block.name} input={block.input} ---")
        elif block.type in ("web_search_tool_result", "web_fetch_tool_result"):
            print(f"--- {block.type} ---")
            print(str(block.content)[:500])
        else:
            print(f"--- {block.type} (unhandled in this spike) ---")
        print()


def main() -> None:
    question = sys.argv[1] if len(sys.argv) > 1 else _DEFAULT_QUESTION
    print(f"Question: {question}\n")

    messages: list[dict] = [{"role": "user", "content": question}]

    with anthropic_client.messages.stream(
        model=app_settings.coach_model,
        max_tokens=8000,
        system=_SYSTEM,
        tools=_TOOLS,
        messages=messages,
    ) as stream:
        response = stream.get_final_message()

    OUTPUT_PATH.write_text(response.to_json())
    print(f"Full raw response saved to {OUTPUT_PATH}\n")
    _print_response(response)

    if response.stop_reason != "tool_use":
        return

    # The model called our client-side submit_ingestion_candidates tool before
    # writing its final answer to the swimmer - the API pauses the turn and
    # waits for a tool_result before it will continue. Sending one back (with
    # the prior assistant turn's blocks replayed exactly as received, since
    # web_search/web_fetch results carry encrypted_content the API needs to
    # restore context on the next turn) lets us observe whether the follow-up
    # answer actually carries citations, which the single-turn run couldn't show.
    tool_results = [
        {"type": "tool_result", "tool_use_id": block.id, "content": "Candidates recorded."}
        for block in response.content
        if block.type == "tool_use"
    ]
    messages.append({"role": "assistant", "content": response.content})
    messages.append({"role": "user", "content": tool_results})

    print("--- continuing turn after submit_ingestion_candidates tool_result ---\n")

    # The prior turn's tool_use blocks were generated from inside the code
    # execution container that dynamic filtering spun up for web_search/
    # web_fetch - the API needs that same container to resolve them, so it
    # rejects a continuation that omits it with a 400 (missing container_id).
    continuation_kwargs = {}
    if response.container is not None:
        continuation_kwargs["container"] = response.container.id

    with anthropic_client.messages.stream(
        model=app_settings.coach_model,
        max_tokens=8000,
        system=_SYSTEM,
        tools=_TOOLS,
        messages=messages,
        **continuation_kwargs,
    ) as stream:
        continuation = stream.get_final_message()

    CONTINUATION_OUTPUT_PATH.write_text(continuation.to_json())
    print(f"Full raw continuation response saved to {CONTINUATION_OUTPUT_PATH}\n")
    _print_response(continuation)


if __name__ == "__main__":
    main()
